[build]
  command = "node build-fix.js"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/og.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/denri.mp4"
  [headers.values]
    Cache-Control = "public, max-age=604800"
